<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PLRENT-8BFM4H2" failures="1" tests="6" name="com.axelerant.testcases.TestCase_Rest_AccountOpen" time="22.127" errors="0" timestamp="2021-12-01T23:39:57 IST" skipped="0">
  <testcase classname="com.axelerant.testcases.TestCase_Rest_AccountOpen" name="tc_createCheckingsAccount" time="4.274"/>
  <system-out>
    <![CDATA[Test Execution started for -> tc_createCheckingsAccount
Create checking account with API
{
    "id": 32103,
    "customerId": 19871,
    "balance": 0,
    "type": "CHECKING"
}
Checking account successfully created with ID : 32103
Test Execution PASSED for -> tc_createCheckingsAccount]]>
  </system-out>
  <testcase classname="com.axelerant.testcases.TestCase_Rest_AccountOpen" name="tc_getCheckingAccountDetails" time="2.275"/>
  <system-out>
    <![CDATA[Test Execution started for -> tc_getCheckingAccountDetails
Verify Cheking account details with API
Checking account details returned correctly
{
    "id": 32103,
    "customerId": 19871,
    "balance": 100.0,
    "type": "CHECKING"
}
Test Execution PASSED for -> tc_getCheckingAccountDetails]]>
  </system-out>
  <testcase classname="com.axelerant.testcases.TestCase_Rest_AccountOpen" name="tc_createSavingssAccount" time="3.134"/>
  <system-out>
    <![CDATA[Test Execution started for -> tc_createSavingssAccount
Create Saving account with API
{
    "id": 32214,
    "customerId": 19871,
    "balance": 0,
    "type": "SAVINGS"
}
Savings account successfully created with ID : 32214
{
    "id": 32214,
    "customerId": 19871,
    "balance": 0,
    "type": "SAVINGS"
}
Test Execution PASSED for -> tc_createSavingssAccount]]>
  </system-out>
  <testcase classname="com.axelerant.testcases.TestCase_Rest_AccountOpen" name="tc_getSavingAccountDetails" time="1.579"/>
  <system-out>
    <![CDATA[Test Execution started for -> tc_getSavingAccountDetails
Verify Saving account details with API
Fetched account details correctly
{
    "id": 32214,
    "customerId": 19871,
    "balance": 100.0,
    "type": "SAVINGS"
}
Test Execution PASSED for -> tc_getSavingAccountDetails]]>
  </system-out>
  <testcase classname="com.axelerant.testcases.TestCase_Rest_AccountOpen" name="tc_billPayFromCheckingsToSavings" time="7.059"/>
  <system-out>
    <![CDATA[Test Execution started for -> tc_billPayFromCheckingsToSavings
Bill Pay using restAPI
Bill payment of $200 is successfull.
{
    "payeeName": "RestApi",
    "amount": 200,
    "accountId": 32103
}
Verifying amount is deducted correctly from checkings account and balance is updated
{
    "id": 32103,
    "customerId": 19871,
    "balance": -100.0,
    "type": "CHECKING"
}
Amount deducted from checkings account is correct
Verify the last transaction amount for Checkings account
Last transaction shows 200 debited from checking account : Debit : 200.0
Test Execution PASSED for -> tc_billPayFromCheckingsToSavings]]>
  </system-out>
  <testcase classname="com.axelerant.testcases.TestCase_Rest_AccountOpen" name="tc_verifySavingsAccountBalanceUpdated" time="3.806">
    <failure message="The following asserts failed:
	expected [true] but found [false],
	expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.axelerant.testcases.TestCase_Rest_AccountOpen.tc_verifySavingsAccountBalanceUpdated(TestCase_Rest_AccountOpen.java:201)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc_verifySavingsAccountBalanceUpdated -->
  <system-out>
    <![CDATA[Test Execution started for -> tc_verifySavingsAccountBalanceUpdated
Verify Saving account balance is updated
{
    "id": 32214,
    "customerId": 19871,
    "balance": 100.0,
    "type": "SAVINGS"
}
Incorrect amount is added to savings account
Verify the last transaction amount for Checkings account
Last transaction does not show $200 added. Last transaction is : Credit : 100.0
Test Execution FAILED for -> tc_verifySavingsAccountBalanceUpdated]]>
  </system-out>
</testsuite> <!-- com.axelerant.testcases.TestCase_Rest_AccountOpen -->
